name: my_bill_generator CI/CD - prod

on:
  push:
    paths:
      - 'my_bill_generator/**'
    branches:
      - main

permissions:
  id-token: write   # For OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::043309334501:role/MyLambdaRole
        aws-region: ap-south-1

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Lambda
      run: |
        cd backend
        pip install --target package -r requirements.txt
        cd package
        zip -r ../function.zip .
        cd ..
        zip -g function.zip main.py templates/

    - name: Deploy Lambda
      run: |
        aws lambda update-function-code \
          --function-name itl-bill-backend-dev \
          --zip-file fileb://backend/function.zip